import Ajv from 'ajv';
import * as referralGet from './referral/referral_get.json';
import * as referralCreate from './referral/referral_create.json';
import * as referralDelete from './referral/referral_delete.json';
import * as referralUpdate from './referral/referral_update.json';
import * as earningsGet from './earnings/earnings_get.json';
import * as earningsMonthlyGet from './earnings/monthly/earnings_monthly_get.json';
import * as referralByCampaignGetAll from './referral/campaign/campaign_getAll.json';
export const ajv = new Ajv();
ajv.addSchema(referralGet, 'referralGet');
ajv.addSchema(referralCreate, 'referralCreate');
ajv.addSchema(referralDelete, 'referralDelete');
ajv.addSchema(referralUpdate, 'referralUpdate');
ajv.addSchema(earningsGet, 'earningsGet');
ajv.addSchema(earningsMonthlyGet, 'earningsMonthlyGet');
ajv.addSchema(referralByCampaignGetAll, 'referralByCampaignGetAll');
