import Ajv from 'ajv';
import * as referralGet from './referral/referral_get.json';
import * as referralCreate from './referral/referral_create.json';
import * as campaignsGet from './campaigns/campaigns_get.json';
import * as campaignsCreate from './campaigns/campaigns_create.json';
export const ajv = new Ajv();
ajv.addSchema(referralGet, 'referralGet');
ajv.addSchema(referralCreate, 'referralCreate');
ajv.addSchema(campaignsGet, 'campaignsGet');
ajv.addSchema(campaignsCreate, 'campaignsCreate');
