frameworkVersion: '2.3.0'
service: cognito-services

plugins:
  - serverless-pseudo-parameters
  - serverless-plugin-warmup

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: us-east-2
  environment:
    NODE_ENV: ${self:provider.stage}
    EMAIL: 'support@brave.credit'
    DOMAIN: 'brave.credit'
    ACCOUNT_ID: '#{AWS::AccountId}'
    REGION: ${self:provider.region}
    DEVAPIURL: 'https://yxd90lcrja.execute-api'
    PRODAPIURL: 'https://k8yolkr65j.execute-api'
    STAGINGAPIURL: 'https://a8tk8rzrpe.execute-api'
    MAILCHIMP_DEQUEUE_SNS_ARN:
      Fn::ImportValue: !Sub '${self:provider.stage}-mailchimp-service-resources-dequeue-topic'
    DEVPOST_REGISTRATION_VERIFICATION_REDIRECT_URL: 'https://dev-app.brave.credit'
    STAGINGPOST_REGISTRATION_VERIFICATION_REDIRECT_URL: 'https://staging-app.brave.credit'
    PRODPOST_REGISTRATION_VERIFICATION_REDIRECT_URL: 'https://app.brave.credit'
  timeout: 60
  apiGateway:
    restApiId: !ImportValue web-api-resources-apigw-id
    restApiRootResourceId: !ImportValue web-api-resources-apigw-rootresource
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'cognito-idp:ListUsers'
        - 'cognito-idp:AdminLinkProviderForUser'
        - 'cognito-idp:AdminCreateUser'
        - 'cognito-idp:AdminSetUserPassword'
        - 'cognito-idp:AdminUpdateUserAttributes'
      Resource: '*'
    - Effect: 'Allow'
      Action:
        - 'ses:SendEmail'
        - 'ses:SendRawEmail'
      Resource: '*'
    - Effect: 'Allow'
      Action:
        - 'sns:publish'
      Resource: '*'
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: '*'

functions:
  presignup:
    handler: handlers/presignup.main
    onError: !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:lambdadeadletterqueue'
    warmup: false
  postAuthentication:
    handler: handlers/postAuthentication.main
    onError: !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:lambdadeadletterqueue'
    warmup: false
  confirmRedirect:
    handler: handlers/confirmRedirect.main
    onError: !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:lambdadeadletterqueue'
    warmup: false
  welcomeUser:
    handler: handlers/welcomeUser.main
    onError: !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:lambdadeadletterqueue'
    warmup: true
  validateUser:
    handler: handlers/validateUser.main
    onError: !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:lambdadeadletterqueue'
    warmup: true
    events:
      - http:
          path: /redirect
          method: get
          cors: true
          integration: lambda-proxy
