# NOTE: update this with your service name
service: credit-report-service-resources

custom:
  settings:
    IDENTITY_IDS:
      dev: 'us-east-2:69169c15-c0c4-4e0b-886c-4afab307e612'
      qa: 'us-east-2:69169c15-c0c4-4e0b-886c-4afab307e612'
      prod: 'us-east-2:ea31caf7-0945-4607-a3c4-0c9942967a32'
    POOL_IDS:
      dev: 'us-east-2_beTcykTM9'
      qa: 'us-east-2_beTcykTM9'
      prod: 'us-east-2_R22DawoAR'

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-2'}
  environment:
    OUR_ENV: ${self:provider.stage}
  vpc:
    securityGroupIds: { 'Fn::Split': [',', { 'Fn::ImportValue': 'agency-services-transunion-vpc-natsecuritygroup' }] }
    subnetIds: { 'Fn::Split': [',', { 'Fn::ImportValue': 'agency-services-transunion-subnets-private' }] }

resources:
  Resources:
    CreditReports:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: 'userId'
            AttributeType: 'S'
          - AttributeName: 'version'
            AttributeType: 'N'
        KeySchema:
          - AttributeName: 'userId'
            KeyType: 'HASH'
          - AttributeName: 'version'
            KeyType: 'RANGE'
        BillingMode: PAY_PER_REQUEST
        TableName: CreditReports
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ${self:provider.stage}-credit-report-service-api

    ApiGatewayAuthorizer:
      Type: AWS::ApiGateway::Authorizer
      Properties:
        Name: credit-reports-authorizer
        Type: COGNITO_USER_POOLS
        IdentitySource: method.request.header.Authorization
        RestApiId:
          Ref: ApiGatewayRestApi
        ProviderARNs:
          - !Sub 'arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${self:custom.settings.POOL_IDS.${opt:stage}}'

    CreditReportsSNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:provider.stage}-credit-reports-topic

    # Create our 'MailchimpQueue' Dead Letter Queue SQS queue
    CreditReportsQueueDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:provider.stage}-credit-reports-dlq
        ReceiveMessageWaitTimeSeconds: 20

    # Create our 'MailchimpQueue' SQS queue
    CreditReportsQueue:
      Type: 'AWS::SQS::Queue'
      Properties:
        QueueName: ${self:provider.stage}-credit-reports-sqs
        ReceiveMessageWaitTimeSeconds: 20
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt
            - CreditReportsQueueDLQ
            - Arn
          maxReceiveCount: 3
        VisibilityTimeout: 720

    # Create our queue policy for the 'MailchimpQueue'
    SnsToCreditReportsQueueSqsPolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Sid: 'allow-sns-messages'
              Effect: Allow
              Principal: '*'
              Resource: !GetAtt
                - CreditReportsQueue
                - Arn
              Action: 'SQS:SendMessage'
              Condition:
                ArnEquals:
                  'aws:SourceArn': !Ref CreditReportsSNSTopic
        Queues:
          - Ref: CreditReportsQueue

    # Create the subscription to the 'queue
    CreditReportsQueueSubscription:
      Type: 'AWS::SNS::Subscription'
      Properties:
        TopicArn: !Ref CreditReportsSNSTopic
        Endpoint: !GetAtt
          - CreditReportsQueue
          - Arn
        Protocol: sqs
        FilterPolicy:
          service:
            - creditreports
        RawMessageDelivery: 'true'

  Outputs:
    CreditReportsTable:
      Description: 'Credit reports table'
      Value: !Ref CreditReports
      Export:
        Name: !Sub '${self:service}-table'
    CreditReportsTableStreamArn:
      Value: { 'Fn::GetAtt': ['CreditReports', 'StreamArn'] }
      Export:
        Name: !Sub '${self:service}-stream'
    ApiGatewayRestApiId:
      Description: 'Credit reports API id'
      Value: !Ref ApiGatewayRestApi
      Export:
        Name: !Sub '${self:service}-apigw-id'
    ApiGatewayRestApiResourceId:
      Description: 'Credit reports API root resource'
      Value: !GetAtt ApiGatewayRestApi.RootResourceId
      Export:
        Name: !Sub '${self:service}-apigw-rootresource'
    ApiGatewayAuthorizorId:
      Description: 'Credit reports API gateway authorizer'
      Value: !Ref ApiGatewayAuthorizer
      Export:
        Name: !Sub '${self:service}-authorizer'
    CreditReportsQueueArn:
      Description: 'Credit reports queue ARN'
      Value: !GetAtt CreditReportsQueue.Arn
      Export:
        Name: !Sub '${self:service}-sqs-arn'
    CreditReportTopicArn:
      Description: 'Credit reports SNS ARN'
      Value: !Ref CreditReportsSNSTopic
      Export:
        Name: !Sub '${self:service}-sns-arn'
