# NOTE: update this with your service name
service: waitlist-service-api

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables
  - serverless-deployment-bucket

custom:
  deploymentBucketName: ${self:service}-deployment-bucket-${opt:stage, 'dev'}
  accessLogBucketName: analytics-access-logging-bucket-${opt:stage, 'dev'}
  deploymentBucket:
    versioning: true
    blockPublicAccess: true
    accessLog:
      bucket: ${self:custom.accessLogBucketName}
      prefix: ""
  bundle:
    aliases:
      - "libs": libs
      - "src": src
      - "tests": tests

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-2'}
  environment:
    STAGE: ${opt:stage, 'dev'}
  apiGateway:
    restApiId: !ImportValue web-api-resources-apigw-id
    restApiRootResourceId: !ImportValue web-api-resources-apigw-rootresource
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  #environment:
  #  SAMPLE_ENV_VAR: ${env:SAMPLE_ENV_VAR}

functions:
  getAccountByEmail:
    handler: src/account/getAccountByEmail.main
    onError: arn:aws:sns:${self:provider.region}:#{AWS::AccountId}:lambdadeadletterqueue
    events:
      - http:
          path: /waitlist/account/{email}
          method: get
          cors: true
          authorizer: aws_iam
