# NOTE: update this with your service name
service: initiative-program-api

# Create an optimized package for our functions
package:
  individually: true

custom:
  bundle:
    linting: false

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-2'}
  environment:
    OUR_ENV: ${self:provider.stage}
  apiGateway:
    restApiId: !ImportValue web-api-resources-apigw-id
    restApiRootResourceId: !ImportValue web-api-resources-apigw-rootresource
    restApiResources:
      initiatives: !ImportValue web-api-resources-apigw-initiativeresource
  iamRoleStatements:
    - Effect: 'Allow'
      Action: 'sns:Publish'
      Resource: '*'
    - Effect: 'Allow'
      Action:
        - dynamodb:ListStreams
        - dynamodb:DescribeTable
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/InitiativePrograms'

functions:
  # User tracked initiatives
  getInitiatives:
    handler: src/http/initiatives/get.main
    onError: !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:lambdadeadletterqueue'
    events:
      - http:
          path: /initiatives
          method: get
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: !ImportValue web-api-resources-apigw-authorizer

  createInitiatives:
    handler: src/http/initiatives/post.main
    onError: !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:lambdadeadletterqueue'
    events:
      - http:
          path: /initiatives
          method: post
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: !ImportValue web-api-resources-apigw-authorizer

  updateInitiatives:
    handler: src/http/initiatives/put.main
    onError: !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:lambdadeadletterqueue'
    events:
      - http:
          path: /initiatives
          method: put
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: !ImportValue web-api-resources-apigw-authorizer

  # for future user to enable event driven arch
  createInitiativeSub:
    handler: src/subs/initiatives/post.main
    onError: !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:lambdadeadletterqueue'
    events:
      - sqs:
          arn:
            Fn::ImportValue: 'initiative-program-resources-sqs-arn'
          batchSize: 1
          maximumBatchingWindow: 5

  updateInitiativeSub:
    handler: src/subs/initiatives/put.main
    onError: !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:lambdadeadletterqueue'
    events:
      - sqs:
          arn:
            Fn::ImportValue: 'initiative-program-resources-sqs-arn'
          batchSize: 1
          maximumBatchingWindow: 5

  metricsSub:
    handler: src/subs/initiatives/metrics.main
    onError: !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:lambdadeadletterqueue'
    events:
      - sns:
          arn:
            Fn::ImportValue: 'credit-report-service-resources-metrics-sns-arn'
          topicName: credit-report-service-resources-metrics-sns-arn

  # # Initiative Programs
  # createPrograms:
  #   handler: src/http/initiatives/programs/post.main
  #   onError: !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:lambdadeadletterqueue'
  #   events:
  #     - http:
  #       path: initiatives/programs
  #       method: post
  #       cors: true
  #       authorizer:
  #         type: COGNITO_USER_POOLS
  #         authorizerId: !ImportValue web-api-resources-apigw-authorizer

  # updatePrograms:
  #   handler: src/http/initiatives/programs/put.main
  #   onError: !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:lambdadeadletterqueue'
  #   events:
  #     - http:
  #       path: initiatives/programs
  #       method: put
  #       cors: true
  #       authorizer:
  #         type: COGNITO_USER_POOLS
  #         authorizerId: !ImportValue web-api-resources-apigw-authorizer
