# NOTE: update this with your service name
service: referral-service

# Create an optimized package for our functions
package:
  individually: true

custom:
  stage: ${opt:stage, self:provider.stage}
  bundle:
    linting: false
    aliases:
      - "libs": libs
      - "src": src
      - "tests": tests
    externals: all
  settings:
    IDENTITY_IDS:
      dev: "us-east-2:69169c15-c0c4-4e0b-886c-4afab307e612"
      qa: "us-east-2:69169c15-c0c4-4e0b-886c-4afab307e612"
      staging: "us-east-2:211dd2a1-db37-4632-a4da-d05c08a80c47"
      prod: "us-east-2:ea31caf7-0945-4607-a3c4-0c9942967a32"
    POOL_IDS:
      dev: "us-east-2_beTcykTM9"
      qa: "us-east-2_beTcykTM9"
      staging: "us-east-2_80pbK9Kx7"
      prod: "us-east-2_R22DawoAR"
    APPDATA:
      dev: "rr5wtr4ev5exlbutrkih3r5lhq:GetAtt:AppDataTable:StreamArn"
      qa: "rr5wtr4ev5exlbutrkih3r5lhq:GetAtt:AppDataTable:StreamArn"
      staging: "mza6aevpsvef5btykbyjp5ffdm:GetAtt:AppDataTable:StreamArn"
      prod: "4tpaga7rzjayhk75opsmpeurme:GetAtt:AppDataTable:StreamArn"

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-2'}
  environment:
    STAGE: ${opt:stage, 'dev'}
    ACCOUNT_ID: !Sub "${AWS::AccountId}"
    IDENTITY_ID: "${self:custom.settings.IDENTITY_IDS.${opt:stage}}"
    POOL_ID: "${self:custom.settings.POOL_IDS.${opt:stage}}"
    REFERRAL_TOPIC_ARN: !Ref ReferralsSNSTopic

resources:
  Resources:
    ReferralsSNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:provider.stage}-referral-sns-topic

    Referrals:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST
        TableName: Referrals
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        KinesisStreamSpecification:
          StreamArn: !ImportValue analytics-raw-data-bucket-arn

    Campaigns:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: "pKey"
            AttributeType: "N"
          - AttributeName: "version"
            AttributeType: "N"
        KeySchema:
          - AttributeName: "pKey"
            KeyType: "HASH"
          - AttributeName: "version"
            KeyType: "RANGE"
        BillingMode: PAY_PER_REQUEST
        TableName: Campaigns
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

  Outputs:
    ReferralsTable:
      Description: "Referrals Table"
      Value: !Ref Referrals
      Export:
        Name: !Sub "${self:service}-referrals"
    ReferralsTableStreamArn:
      Value: { "Fn::GetAtt": ["Referrals", "StreamArn"] }
      Export:
        Name: !Sub "${self:service}-referrals-stream"
    CampaignsTable:
      Description: "Campaigns Table"
      Value: !Ref Campaigns
      Export:
        Name: !Sub "${self:service}-campaigns"
    CampaignsTableStreamArn:
      Value: { "Fn::GetAtt": ["Campaigns", "StreamArn"] }
      Export:
        Name: !Sub "${self:service}-campaigns-stream"
    ReferralsSNSTopicArn:
      Description: "Referrals sub topic"
      Value: !Ref ReferralsSNSTopic
      Export:
        Name: !Sub "${self:service}-referrals-sns-topic"
