# NOTE: update this with your service name
service: referral-service

# Create an optimized package for our functions
package:
  individually: true

custom:
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-2'}
  environment:
    STAGE: ${opt:stage, 'dev'}

resources:
  Resources:
    ReferralsSNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:provider.stage}-referral-sns-topic

    Referrals:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST
        TableName: Referrals
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        KinesisStreamSpecification:
          StreamArn: !ImportValue analytics-raw-data-bucket-arn

    Campaigns:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: "pKey"
            AttributeType: "N"
          - AttributeName: "version"
            AttributeType: "N"
        KeySchema:
          - AttributeName: "pKey"
            KeyType: "HASH"
          - AttributeName: "version"
            KeyType: "RANGE"
        BillingMode: PAY_PER_REQUEST
        TableName: Campaigns
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

  Outputs:
    ReferralsTable:
      Description: "Referrals Table"
      Value: !Ref Referrals
      Export:
        Name: !Sub "${self:service}-referrals"
    ReferralsTableStreamArn:
      Value: { "Fn::GetAtt": ["Referrals", "StreamArn"] }
      Export:
        Name: !Sub "${self:service}-referrals-stream"
    CampaignsTable:
      Description: "Campaigns Table"
      Value: !Ref Campaigns
      Export:
        Name: !Sub "${self:service}-campaigns"
    CampaignsTableStreamArn:
      Value: { "Fn::GetAtt": ["Campaigns", "StreamArn"] }
      Export:
        Name: !Sub "${self:service}-campaigns-stream"
    ReferralsSNSTopicArn:
      Description: "Referrals sub topic"
      Value: !Ref ReferralsSNSTopic
      Export:
        Name: !Sub "${self:service}-referrals-sns-topic"
