export enum MailchimpTriggerEmails {
  OnboardingDropOut = 'nt-04-drop-out-of-onboarding',
  DisputeSubmitted = 'd01-dispute-submitted',
  DisputeResultsReady = 'd02-dispute-results-ready',
  ReportRefreshed = 't21-credit-report-refresh',
  ReferralCode = 'r01-referral-code',
  MarketingDefaults = 'marketing-defaults',
  LessThan650 = 'marketing-less-than-650',
  EnrollmentTag = 'marketing-enrollments',
  MortgageTag = 'marketing-mortgages',
  AutoLoanTag = 'marketing-auto-loans',
  CollectionsTag = 'marketing-collections',
  NegativeTag = 'marketing-negative-accounts',
  StudentLoanTag = 'marketing-student-loans',
  DisputedTag = 'marketing-disputed',
  ChangeAccounts = 'change-accounts',
  ChangeAddresses = 'change-addresses',
  ChangeEmployers = 'change-employers',
  ChangeNames = 'change-names',
  ChangeCollections = 'change-collections',
  ChangeNegatives = 'change-negatives',
  ChangeCreditScore = 'change-credit-score',
  Over650Score = 'over-650-score',
  GoalChosen = 'goal-chosen',
  GoalTaskStatus = 'goal-task-status',
  GoalProgress = 'goal-progress',
}
